[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form handling settings
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Redirect rule for form submissions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
